const typography = {
  fontFamily: ["Roboto", "DrukTextWideCyr"].join(","),
  h1: {
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: "64px",
    lineHeight: "76px",
    fontFamily: "Roboto",
  },
  h2: {
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: "36px",
    lineHeight: "44px",
    fontFamily: "Roboto",
  },
  h3: {
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: "28px",
    lineHeight: "36px",
    fontFamily: "Roboto",
  },
  h4: {
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: "20px",
    lineHeight: "28px",
    fontFamily: "Roboto",
  },
  body1: {
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "18px",
    lineHeight: "28px",
    fontFamily: "Roboto",
  },
  body2: {
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: "16px",
    lineHeight: "24px",
    fontFamily: "Roboto",
  },
  body3: {
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: "14px",
    lineHeight: "20px",
    fontFamily: "Roboto",
  },
  text1: {
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: "16px",
    lineHeight: "24px",
    fontFamily: "Roboto",
  },
  text2: {
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: "12px",
    lineHeight: "16px",
    fontFamily: "Roboto",
  },
  extraH1: {
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "48px",
    lineHeight: "46px",
    fontFamily: "DrukTextWideCyr",
  },
  extraH2: {
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "40px",
    lineHeight: "44px",
    fontFamily: "DrukTextWideCyr",
  },
  extraH3: {
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "28px",
    lineHeight: "36px",
    fontFamily: "DrukTextWideCyr",
  },
  extraH4: {
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "20px",
    lineHeight: "28px",
    fontFamily: "DrukTextWideCyr",
  },
  extraBody1: {
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "18px",
    lineHeight: "28px",
    fontFamily: "DrukTextWideCyr",
  },
  extraBody2: {
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "16px",
    lineHeight: "24px",
    fontFamily: "DrukTextWideCyr",
  },
  extraBody3: {
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "14px",
    lineHeight: "20px",
    fontFamily: "DrukTextWideCyr",
  },
};

export default typography;
